# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\git\ffmpeg\addTask.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_addTask(object):
    def setupUi(self, addTask):
        addTask.setObjectName("addTask")
        addTask.resize(689, 142)
        addTask.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(addTask)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(addTask)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(addTask)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox_protocol = QtWidgets.QComboBox(addTask)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboBox_protocol.setFont(font)
        self.comboBox_protocol.setObjectName("comboBox_protocol")
        self.comboBox_protocol.addItem("")
        self.comboBox_protocol.addItem("")
        self.comboBox_protocol.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_protocol)
        self.label_2 = QtWidgets.QLabel(addTask)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_multiIp = QtWidgets.QLineEdit(addTask)
        self.lineEdit_multiIp.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_multiIp.setFont(font)
        self.lineEdit_multiIp.setObjectName("lineEdit_multiIp")
        self.horizontalLayout.addWidget(self.lineEdit_multiIp)
        self.label_4 = QtWidgets.QLabel(addTask)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit_port = QtWidgets.QLineEdit(addTask)
        self.lineEdit_port.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_port.setFont(font)
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.horizontalLayout.addWidget(self.lineEdit_port)
        self.label_6 = QtWidgets.QLabel(addTask)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.comboBox_videoFormat = QtWidgets.QComboBox(addTask)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboBox_videoFormat.setFont(font)
        self.comboBox_videoFormat.setObjectName("comboBox_videoFormat")
        self.comboBox_videoFormat.addItem("")
        self.comboBox_videoFormat.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_videoFormat)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(addTask)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.lineEdit_path = QtWidgets.QLineEdit(addTask)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_path.setFont(font)
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.horizontalLayout_3.addWidget(self.lineEdit_path)
        self.pushButton_openPath = QtWidgets.QPushButton(addTask)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_openPath.setFont(font)
        self.pushButton_openPath.setObjectName("pushButton_openPath")
        self.horizontalLayout_3.addWidget(self.pushButton_openPath)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.pushButton_ok = QtWidgets.QPushButton(addTask)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_ok.setFont(font)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_3.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(addTask)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_3.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(addTask)
        QtCore.QMetaObject.connectSlotsByName(addTask)

    def retranslateUi(self, addTask):
        _translate = QtCore.QCoreApplication.translate
        addTask.setWindowTitle(_translate("addTask", "Dialog"))
        self.label.setText(_translate("addTask", "配置推流任务"))
        self.label_3.setText(_translate("addTask", "协议："))
        self.comboBox_protocol.setItemText(0, _translate("addTask", "UDP"))
        self.comboBox_protocol.setItemText(1, _translate("addTask", "RTP"))
        self.comboBox_protocol.setItemText(2, _translate("addTask", "RTMP"))
        self.label_2.setText(_translate("addTask", "组播地址："))
        self.lineEdit_multiIp.setText(_translate("addTask", "255.255.255.255"))
        self.label_4.setText(_translate("addTask", "端口号："))
        self.lineEdit_port.setText(_translate("addTask", "65535"))
        self.label_6.setText(_translate("addTask", "视频格式："))
        self.comboBox_videoFormat.setItemText(0, _translate("addTask", "TS"))
        self.comboBox_videoFormat.setItemText(1, _translate("addTask", "MPEG4"))
        self.label_5.setText(_translate("addTask", "选择文件路径："))
        self.lineEdit_path.setText(_translate("addTask", "撒点发送的防"))
        self.pushButton_openPath.setText(_translate("addTask", "浏览"))
        self.pushButton_ok.setText(_translate("addTask", "确定"))
        self.pushButton_cancel.setText(_translate("addTask", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addTask = QtWidgets.QDialog()
    ui = Ui_addTask()
    ui.setupUi(addTask)
    addTask.show()
    sys.exit(app.exec_())

